### ISSUE TITLE
PackagesNotFoundError: Cannot install r-sf using conda on osx-arm64

### ISSUE THREAD

**Issue by marcopeix** [conda-forge/r-sf-feedstock#121]
### Comment:

My virtual env has Python 3.10. I can successfully install r-base, but r-sf never works. It gives this error:

```
PackagesNotFoundError: The following packages are not available from current channels:

  - r-sf

Current channels:

  - https://conda.anaconda.org/conda-forge
  - defaults
```
  
  I tried following the instructions in the repo and using the urls in [Anaconda](https://anaconda.org/conda-forge/r-sf), but nothing worked.
  
  I am working on MacOS.

**Comment by mfansler** [comment]
This has been an open issue, but notably the latest migrator did pass for **osx-arm64**, so may just need some troubleshooting for the other builds. I will try to work on this if I have time this week.

**Comment by mfansler** [comment]
Done. Typically takes 1-2 hours to rebuild, upload, and get indexed.
