### ISSUE TITLE
latest r-sf not available yet for conda

### ISSUE THREAD

**Issue by KoichiHashikawa** [conda-forge/r-sf-feedstock#28]
Hi!

I am not sure this is the right place for question, but we are glad if the latest r-sf 7.7 will be available in conda at somepoint.

thanks for considering!

Koichi

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by r-barnes** [comment]
I am also wondering this.

**Comment by dpryan79** [comment]
Once someone can get the thing to build it'll be available: https://github.com/conda-forge/r-sf-feedstock/pull/29
